config/routes.rb
Rails.application.routes.draw do
	root 'dashboard#index'
  devise_for :admins

  resources :categories
  resources :orders do
    patch :handle, on: :member
  end
  resources :products
  resources :stores
end

app/models/store.rb
class Store < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
  validates :city, presence: true

  alias_attribute :to_s, :name
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:edit, :update, :destroy]

  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)

    if @store.save
      redirect_to stores_url, notice: "#{@store} 创建成功。"
    else
      render :new
    end
  end

  def update
    if @store.update(store_params)
      redirect_to stores_url, notice: "#{@store} 修改成功。"
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_url, notice: "#{@store} 删除成功。"
  end

  private
  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :city, :address, :phone)
  end
end

app/views/stores/_form.html.erb
<%= simple_form_for(@store) do |f| %>
  <div class="form-inputs">
    <%= f.input :city, label: "所在城市" %>
    <%= f.input :name, label: "门店名" %>
    <%= f.input :address, label: "地址" %>
    <%= f.input :phone, label: "联系电话" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "提交表单", class: "btn-primary" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h3>修改门店信息</h3>

<%= render 'form' %>

app/views/stores/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr class="active">
      <th>所在城市</th>
      <th>门店名</th>
      <th>门店地址</th>
      <th>联系电话</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @stores.group_by(&:city).each do |city, stores| %>
      <% stores.each_with_index do |store, index| %>
        <tr>
          <% if index == 0 %>
            <td rowspan="<%= stores.count %>"><%= city %></td>
          <% end %>
          <td><strong><%= store.name %></strong></td>
          <td><%= store.address %></td>
          <td><%= store.phone %></td>
          <td>
            <%= link_to '修改', edit_store_path(store), class: "btn btn-xs btn-primary" %>
            <%= link_to '删除', store, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: '确定要删除这个门店吗？' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to '创建新门店', new_store_path, class: "btn btn-large btn-primary" %>

app/views/stores/new.html.erb
<h3>创建门店</h3>

<%= render 'form' %>