config/routes.rb
Rails.application.routes.draw do
	root 'dashboard#index'
  devise_for :admins

  resources :categories
  resources :orders do
    patch :handle, on: :member
  end
  resources :products
  resources :stores
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  belongs_to :takeout_store, class_name: "Store", foreign_key: "takeout_store_id"

  scope :unprocessed, -> { where(state: "unprocessed") }

	validates_presence_of :contact_name, :contact_phone
  
  accepts_nested_attributes_for :order_items, allow_destroy: true

  alias_attribute :to_s, :serial_number

  before_create :set_state

  STATES = ["unprocessed", "processed"]

  def handle
    raise "订单#{serial_number}已经被处理了" unless unprocessed?
    update_column(:state, "processed")
  end

  def serial_number
    "MZ-%.6d" % id 
  end

  def human_state_name
    case state
    when "unprocessed" then "未处理"
    when "processed" then "已处理"
    end
  end

  def unprocessed?
    state == "unprocessed"
  end

  private
  def set_state
    self.state = "unprocessed"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :handle]

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order, notice: "订单#{@order} 创建成功。"
    else
      render :new
    end
  end

  def update
    if @order.update(order_params)
      redirect_to @order, notice: "订单#{@order} 修改成功。"
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_url, notice: "订单#{@order} 删除成功。"
  end

  def handle
    @order.handle
    redirect_to orders_url, notice: "订单#{@order} 状态已更新为'已处理'。"
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, :contact_name, :contact_phone, :takeout_time, :takeout_store_id, :shipping_address, :amount, :note, order_items_attributes: [:id, :product_id, :pound, :blessing, :note, :_destroy])
  end
end

app/views/orders/_form.html.erb
<%= simple_form_for @order , html: { class: 'form-horizontal order-form' }, wrapper: :horizontal_form do |f| %>
  <h4>联系信息</h4>
  <div class="well well-sm">
    <%= f.input :contact_name, label: "姓名" %>
    <%= f.input :contact_phone, label: "手机号码" %>
  </div>

  <h4>配送/取货信息</h4>
  <div class="well well-sm">
    <%= f.input :takeout_store_id, label: "取货门店", as: :grouped_select, include_blank: true, collection: Store.all.group_by(&:city), group_method: :last, group_label_method: :first %>
    
    <%= f.input :takeout_time, label: "取货时间" %>

    <%= f.input :shipping_address, label: "送货地址" %>
  </div>

  <h4>订单项</h4>
  <%= f.simple_fields_for :order_items do |f| %>
    <%= render "orders/order_item_fields", f: f %>
  <% end %>
  <%= link_to_add_fields "添加订单项", f, :order_items, "orders/" %>

  <h4>其他信息</h4>
  <div class="well well-sm">
    <%= f.input :amount, label: "总额" %>
    <%= f.input :note, label: "备注" %>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, "提交表单", class: 'btn-primary' %>
      <%= link_to "返回订单列表", orders_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/orders/_order_item_fields.html.erb
<fieldset class="well well-sm" style="<%= "display:none;" if f.object._destroy %>">
  <%= f.hidden_field :_destroy %>
  <%= f.input :product_id, label: "商品", collection: Category.all, as: :grouped_select, group_method: :products %>
	<%= f.input :pound, label: "磅数" %>
	<%= f.input :blessing, label: "祝福语" %>
	<%= f.input :note, label: "备注" %>
  <%= link_to "删除订单项", '#', class: "remove_fields btn btn-xs btn-danger pull-right" %>
</fieldset>

app/views/orders/_order_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>订单<%= order.serial_number %></strong><small>( <%= order.human_state_name %> )</small>
    <%= link_to glyphicon_tag("ok", "已处理"), handle_order_path(order), method: :patch, class: "btn btn-xs btn-success pull-right" %>
  </div>
  <div class="panel-body">
    
    <ul>
      <li>创建时间: <%= l order.created_at, format: :short %></li>
      <li>联系人: <%= order.contact_name %></li>
      <li>联系电话: <%= order.contact_phone %></li>
      <li>配送地址: <%= order.shipping_address %></li>
      <li>取货门店: <%= order.takeout_store %></li>
      <li>取货时间: <%= order.takeout_time %></li>
      <li>备注: <%= order.note %></li>
    </ul>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr class="active">
        <th>商品</th>
        <th>磅数</th>
        <th>祝福语</th>
        <th>备注</th>
      </tr>
    </thead>

    <tbody>
      <% order.order_items.each do |item| %>
        <tr>
          <td><%= item.product %></td>
          <td><%= item.pound %></td>
          <td><%= item.blessing %></td>
          <td><%= item.note %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td class="text-danger text-right" colspan="99"><strong><%= number_to_currency(order.amount, unit: "￥") %></strong></td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/orders/edit.html.erb
<h3>修改订单信息</h3>

<%= render 'form' %>

app/views/orders/index.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>订单号</th>
      <th>联系信息</th>
      <th>配送/取货信息</th>
      <th>订单总额</th>
      <th>创建时间</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr class="<%= "warning" if order.unprocessed? %>">
        <td><%= order.serial_number %></td>
        <td><%= order.contact_name %>(<%=  order.contact_phone %>)</td>
        <td>
          <%= order.takeout_time %>
          <%= order.takeout_store %>
          <%= order.shipping_address %>
        </td>
        <td><%= number_to_currency(order.amount, unit: "￥") %></td>
				<td><%= l order.created_at, format: :short %></td>
        <td>
          <%= link_to '订单详情', order, class: "btn btn-default btn-xs" %>
          <%= link_to '修改', edit_order_path(order), class: "btn btn-primary btn-xs" %>
          <%= link_to '删除', order, method: :delete, data: { confirm: '确定要删除这张订单吗?' }, class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="99">
        <ul class="list-unstyled notes">
          <li><span class="new-order"></span>: 代表这张订单是一张未处理的订单。</td></li>
        </ul>
      </td>
    </tr>
  </tfoot>
</table>

<%= link_to '创建新订单', new_order_path, class: "btn btn-large btn-primary" %>

app/views/orders/new.html.erb
<h3>创建新订单</h3>

<%= render 'form' %>

app/views/orders/show.html.erb
<%= render "order_panel", order: @order %>

<%= link_to '修改当前订单', edit_order_path(@order), class: "btn btn-primary" %>
<%= link_to '返回订单列表', orders_path, class: "btn btn-default" %>