config/routes.rb
Rails.application.routes.draw do
	root 'dashboard#index'
  devise_for :admins

  resources :categories
  resources :orders do
    patch :handle, on: :member
  end
  resources :products
  resources :stores
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

	validates :name, presence: true, uniqueness: true
  validates :category, presence: true

  alias_attribute :to_s, :name
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url, notice: "商品 #{@product} 创建成功。"
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to products_url, notice: "商品 #{@product} 修改成功。"
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: "商品 #{@product} 删除成功。"
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :category_id)
  end
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <div class="form-inputs">
    <%= f.association :category, label: "商品种类" %>
    <%= f.input :name, label: "商品名" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "提交表单", class: "btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h3>修改商品信息</h3>

<%= render 'form' %>

app/views/products/index.html.erb
<h4>商品种类列表</h4>
<table class="table table-bordered">
  <thead>
    <tr class="active">
      <th>名称</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><strong><%= category.name %></strong></td>
        <td>
          <%= link_to '修改', edit_category_path(category), class: "btn btn-xs btn-primary" %>
          <%= link_to '删除', category, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: '确定要删除这个商品种类吗？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="99"><%= link_to '创建新商品种类', new_category_path, class: "btn btn-large btn-primary" %></td>
    </tr>
  </tfoot>
</table>

<h4>商品列表</h4>
<table class="table table-bordered">
  <thead>
    <tr class="active">
      <th>种类</th>
      <th>商品名</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @products.group_by(&:category).each do |category, products| %>
      <% products.each_with_index do |product, index| %>
        <tr>
          <% if index == 0 %>
            <td rowspan="<%= products.count %>"><%= category %></td>
          <% end %>
          <td><strong><%= product.name %></strong></td>
          <td>
            <%= link_to '修改', edit_product_path(product), class: "btn btn-xs btn-primary" %>
            <%= link_to '删除', product, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: '确定要删除这个商品吗？' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="99"><%= link_to '创建新商品', new_product_path, class: "btn btn-large btn-primary" %></td>
    </tr>
  </tfoot>
</table>

app/views/products/new.html.erb
<h3>创建商品</h3>

<%= render 'form' %>