config/routes.rb
Rails.application.routes.draw do
	root 'dashboard#index'
  devise_for :admins

  resources :categories
  resources :orders do
    patch :handle, on: :member
  end
  resources :products
  resources :stores
end

app/views/layouts/_flash_content.html.erb
<div class="flash">
  <% flash.each do |type, message| -%>
    <div class="alert <%= alert_class(type) %>">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= message %>
		</div>
  <% end -%>
</div>

app/views/layouts/_footer.html.erb
<footer class="ks-footer">
  <p>&copy; <%= Time.now.year %> <%= link_to "Zernel Guan", "mailto:itzernel@gmail.com" %></p>
</footer>

app/views/layouts/_navbar.html.erb
<% if admin_signed_in? %>
  <ul class="nav nav-tabs custom-navtabs">
    <%= tab_nav_link_to :dashboard, "主页", root_path %>
    <%= tab_nav_link_to :orders, "订单", orders_path %>
    <%= tab_nav_link_to :products, "商品", products_path %>
    <%= tab_nav_link_to :stores, "门店", stores_path %>
  </ul>
<% end %>

app/views/layouts/_topbar.html.erb
<header class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Mycharm OMS", root_path, class: "navbar-brand" %>
		</div>
		<nav>
      <% if admin_signed_in? %>
        <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "btn btn-default navbar-btn navbar-right" %>
        <p class="navbar-text navbar-right" style="margin-right:15px;">Signed in with Admin <%= current_admin %></p>
      <% end %>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Mycharm OMS" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>

  <body>
		<%= render "layouts/topbar" %>
		<%= yield(:header) if content_for?(:header) %>

		<div class="container">
			<%= render "layouts/navbar" %>
      <%= render "layouts/flash_content" %>
			<%= yield %>
		</div>

		<%= render "layouts/footer" %>
	</body>
</html>